version: 2
jobs:
  build:
    docker:
#      - image: circleci/openjdk:8u181-jdk # java 8
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Prepare Python env
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run Pyhton tests
          command: |
            pipenv shell
            python src/test/python/testAll.py
      - run:
          name: Run tests
          command: build/sbt test  # make it +test to cross-scala compile
