version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk # java 8
    steps:
      - checkout
      - run:
          name: Prepare Python env
          command: |
            sudo apt-get install python
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run Pyhton tests
          command: pipenv run python src/test/python/testAll.py
      - run:
          name: Run Scala/Java tests
          command: build/sbt test  # make it +test to cross-scala compile
