version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk # java 8
    steps:
      - checkout
      - run:
          name: Run tests
#          command: build/sbt test  # make it +test to cross-scala compile
          command: ls
  test: # this job is for python API tests
    docker:
      - image: circleci/python:3.7.4  # python 3.7
    steps:
      - checkout
      - run:
          name: Prepare Python env
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run Pyhton tests
          command: |
            pipenv run python src/test/python/testAll.py

#workflows:  # this is the config for sequential jobs
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
