version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build --tag=pydeltalake .
      - run:
          name: Run Scala/Java and Python tests
          command: docker run pydeltalake:latest
