version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9.0.4-jdk # java 9
      - image: circleci/openjdk:8u171-jdk # java 8
    steps:
      - checkout
      - run:
          name: See javac
          command: sudo update-alternatives; sudo update-alternatives; echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.circlerc
      - run:
          name: Run tests
          command: build/sbt test  # make it +test to cross-scala compile
