version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9.0.4-jdk # java 9
      - image: circleci/openjdk:8u181-jdk # java 8
    dependencies:
      pre:
        - sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0/bin/java
        - sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
        - echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.circlerc
    steps:
      - checkout
      - run:
          name: Run tests
          command: build/sbt test  # make it +test to cross-scala compile
