version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9.0.4-jdk # java 9
      - image: circleci/openjdk:8u171-jdk # java 8
    steps:
      - checkout
      - run:
          name: See javaHome
          command: ls $JAVA_HOME
      - run:
          name: See javac
          command: which javac | xargs ls -al 
      - run:
          name: See javaHome
          command: ls /usr/lib/jvm
      - run:
          name: Run tests
          command: build/sbt test  # make it +test to cross-scala compile
