version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk # java 8
    steps:
      - checkout
      - run:
          name: Prepare Python env # install python3.7, python3-pip and pipenv for pyspark.
          command: |
            sudo apt-get update
            sudo apt install python3-pip --fix-missing
            sudo pip3 install pipenv
            pipenv install
      - run:
          name: Run Pyhton tests # build the Delta Lake and run the python tests
          command: |
            build/sbt "++2.11.12 package"
            pipenv run spark-submit --jars target/scala-2.11/delta-core_2.11-0.3.1-SNAPSHOT.jar src/test/python/test_deltatable.py
      - run:
          name: Run Scala/Java tests
          command: build/sbt test  # make it +test to cross-scala compile
