version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk # java 8
    steps:
      - checkout
      - run:
          name: Prepare Python env
          command: |
            sudo apt update
            sudo apt install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa

            sudo apt install python3.7
            sudo apt install python3-pip
            sudo pip3 install pyspark
      - run:
          name: Run Pyhton tests
          command: |
            build/sbt "++2.11.12 package"
            spark-submit src/test/python/testAll.py --jars $PWD/target/scala-2.11/delta-core_2.11-0.3.1-SNAPSHOT.jar
      - run:
          name: Run Scala/Java tests
          command: build/sbt test  # make it +test to cross-scala compile
