name: Add new pull requests to Backlog (External)

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  automate-new-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: oss-eng-delta-ecosystem
          column: Backlog (External)
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}