name: Move updated pull requests to Needs Review

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [synchronize]

jobs:
  automate-updated-pull-requests:
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@2af3cf061aeca8ac6ab40a960eee1968a7f9ce0e
        with:
          project: oss-eng-delta-ecosystem
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}